### PR TITLE
Add lxml ^5.0.0 support while keeping the ^4.6.2 support

### LINKED ISSUE #74: Work with lxml 5.0.0
lxml has bumped its major version due to an upstream (libxml2) breaking change.

https://github.com/lxml/lxml/blob/1a4362be12c99ec22f9859f3fe6455952256539f/CHANGES.txt#L60-L64

### PR DESCRIPTION
**Pull request by Rongronggg9**
Fixes #74

### CODE REVIEW

**Comment by kurtmckee** [comment]
@Rongronggg9 I modified the commit, as the minimum dependencies are already getting tested locally and in CI by existing tox environments.

Thanks for this PR!

**Comment by Rongronggg9** [comment]
Thanks for merging! Could you backport it and make a release? So that the released version won't conflict with lxml5.

**Comment by kurtmckee** [comment]
I think I can release v0.20.0 from `main`, so I want to clarify what you mean.

When you say "backport it", are you asking me to cherry-pick this commit into a v0.19.1 release from the `releases` branch?

**Comment by Rongronggg9** [comment]
> release v0.20.0 from `main`

That's sufficient. Thanks!

**Pull request merged**
